// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiObjectResponse, ApiResponse, FundDetailData, FundDetailParams, FundPortfolioItem, FundPortfolioParams, FundRankingItem, FundRankingParams } from '../../data/types';

/** Returns a fund's **profile metadata**. **Included fields:** X accounts, team members, recent research, invested project count. This does NOT return the list of investments — use `/fund/portfolio` for that. **Lookup:** by UUID (`id`) or name (`q`). Returns 404 if not found. */
export function useFundDetail(params?: FundDetailParams) {
  return useQuery({
    queryKey: ['fund-detail', params],
    queryFn: () => proxyGet<ApiObjectResponse<FundDetailData>>('fund/detail', params as any),
  });
}

/** Returns investment rounds for a fund's portfolio, sorted by date (newest first). A project may appear multiple times if the fund participated in multiple rounds. **Included fields:** project name, logo, date, raise amount, lead investor status. **Lookup:** by UUID (`id`) or name (`q`). */
export function useInfiniteFundPortfolio(params?: Omit<FundPortfolioParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['fund-portfolio', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<FundPortfolioItem>>('fund/portfolio', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Returns top-ranked funds by a specified metric. **Available metrics:** `tier` (lower is better), `portfolio_count` (number of invested projects). */
export function useInfiniteFundRanking(params: Omit<FundRankingParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['fund-ranking', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<FundRankingItem>>('fund/ranking', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

