// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiResponse, KalshiEventsItem, KalshiEventsParams, KalshiMarketsItem, KalshiMarketsParams, KalshiOpenInterestItem, KalshiOpenInterestParams, KalshiPricesItem, KalshiPricesParams, KalshiRankingItem, KalshiRankingParams, KalshiTradesItem, KalshiTradesParams, KalshiVolumesItem, KalshiVolumesParams } from '../../data/types';

/** Returns Kalshi events with nested markets, optionally filtered by `event_ticker`. Each event includes market count and a list of markets. **Data refresh:** ~30 minutes */
export function useInfiniteKalshiEvents(params: Omit<KalshiEventsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['kalshi-events', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<KalshiEventsItem>>('prediction-market/kalshi/events', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Returns Kalshi markets, optionally filtered by `market_ticker`. Each market includes price, volume, and status. **Data refresh:** ~30 minutes */
export function useInfiniteKalshiMarkets(params: Omit<KalshiMarketsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['kalshi-markets', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<KalshiMarketsItem>>('prediction-market/kalshi/markets', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Returns daily open interest history for a Kalshi market, filtered by `time_range`. **Data refresh:** ~30 minutes */
export function useInfiniteKalshiOpenInterest(params: Omit<KalshiOpenInterestParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['kalshi-open-interest', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<KalshiOpenInterestItem>>('prediction-market/kalshi/open-interest', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Returns price history for a Kalshi market. **Interval options:** - `interval=1d` — daily OHLC from market reports (~30 min delay) - `interval=latest` — real-time price from trades **Data refresh:** ~30 minutes (daily), real-time (latest) */
export function useInfiniteKalshiPrices(params: Omit<KalshiPricesParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['kalshi-prices', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<KalshiPricesItem>>('prediction-market/kalshi/prices', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Returns top-ranked Kalshi markets by last day's `notional_volume_usd` or `open_interest`. **Filters:** `status`. **Data refresh:** ~30 minutes */
export function useInfiniteKalshiRanking(params?: Omit<KalshiRankingParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['kalshi-ranking', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<KalshiRankingItem>>('prediction-market/kalshi/ranking', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Returns individual trade records for a Kalshi market. **Filters:** `taker_side`, `min_contracts`, and date range. **Sort:** `timestamp` or `num_contracts`. **Data refresh:** real-time */
export function useInfiniteKalshiTrades(params: Omit<KalshiTradesParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['kalshi-trades', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<KalshiTradesItem>>('prediction-market/kalshi/trades', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Returns daily trading volume history for a Kalshi market, filtered by `time_range`. **Data refresh:** ~30 minutes */
export function useInfiniteKalshiVolumes(params: Omit<KalshiVolumesParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['kalshi-volumes', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<KalshiVolumesItem>>('prediction-market/kalshi/volumes', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

