// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiResponse, KalshiEventsItem, KalshiEventsParams, KalshiMarketsItem, KalshiMarketsParams, KalshiOpenInterestItem, KalshiOpenInterestParams, KalshiPricesItem, KalshiPricesParams, KalshiRankingItem, KalshiRankingParams, KalshiTradesItem, KalshiTradesParams, KalshiVolumesItem, KalshiVolumesParams } from '../../data/types';

/** Get Kalshi events with nested markets, optionally filtered by `event_ticker`. Each event includes market count and a list of markets. Data refresh: ~30 minutes */
export function useInfiniteKalshiEvents(params?: Omit<KalshiEventsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['kalshi-events', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<KalshiEventsItem>>('kalshi/events', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get Kalshi markets, optionally filtered by `market_ticker`. Each market includes price, volume, and status. Data refresh: ~30 minutes */
export function useInfiniteKalshiMarkets(params?: Omit<KalshiMarketsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['kalshi-markets', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<KalshiMarketsItem>>('kalshi/markets', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get daily open interest history for a Kalshi market filtered by `time_range`. Data refresh: ~30 minutes */
export function useKalshiOpenInterest(params?: KalshiOpenInterestParams) {
  return useQuery({
    queryKey: ['kalshi-open-interest', params],
    queryFn: () => proxyGet<ApiResponse<KalshiOpenInterestItem>>('kalshi/open-interest', params as any),
  });
}

/** Get price history for a Kalshi market. Use `interval=1d` for daily OHLC from market reports (~30 min delay), or `interval=latest` for real-time price from trades. Data refresh: ~30 minutes (daily), real-time (latest) */
export function useKalshiPrices(params?: KalshiPricesParams) {
  return useQuery({
    queryKey: ['kalshi-prices', params],
    queryFn: () => proxyGet<ApiResponse<KalshiPricesItem>>('kalshi/prices', params as any),
  });
}

/** Get top-ranked Kalshi markets by last day's `notional_volume_usd` or `open_interest`. Filter by `status`. Data refresh: ~30 minutes */
export function useInfiniteKalshiRanking(params?: Omit<KalshiRankingParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['kalshi-ranking', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<KalshiRankingItem>>('kalshi/ranking', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get individual trade records for a Kalshi market. Filter by `taker_side`, `min_contracts`, and date range. Sort by `timestamp` or `num_contracts`. Data refresh: real-time */
export function useInfiniteKalshiTrades(params?: Omit<KalshiTradesParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['kalshi-trades', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<KalshiTradesItem>>('kalshi/trades', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get daily trading volume history for a Kalshi market filtered by `time_range`. Data refresh: ~30 minutes */
export function useKalshiVolumes(params?: KalshiVolumesParams) {
  return useQuery({
    queryKey: ['kalshi-volumes', params],
    queryFn: () => proxyGet<ApiResponse<KalshiVolumesItem>>('kalshi/volumes', params as any),
  });
}

