// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiResponse, MarketEtfItem, MarketEtfParams, MarketFearGreedItem, MarketFearGreedParams, MarketFuturesItem, MarketFuturesParams, MarketLiquidationChartItem, MarketLiquidationChartParams, MarketLiquidationExchangeListItem, MarketLiquidationExchangeListParams, MarketLiquidationOrderItem, MarketLiquidationOrderParams, MarketOnchainIndicatorItem, MarketOnchainIndicatorParams, MarketOptionsItem, MarketOptionsParams, MarketPriceIndicatorItem, MarketPriceIndicatorParams, MarketPriceItem, MarketPriceParams, MarketRankingItem, MarketRankingParams } from '../../data/types';

/** Returns daily ETF flow history for US spot ETFs. **Included fields:** net flow (USD), token price, per-ticker breakdown. Sorted by date descending. `symbol`: `BTC` or `ETH`. */
export function useMarketEtf(params: MarketEtfParams) {
  return useQuery({
    queryKey: ['market-etf', params],
    queryFn: () => proxyGet<ApiResponse<MarketEtfItem>>('market/etf', params as any),
  });
}

/** Returns Bitcoin Fear & Greed Index history. **Included fields:** index value (0-100), classification label, BTC price at each data point. Sorted newest-first. Use `from`/`to` to filter by date range. */
export function useMarketFearGreed(params?: MarketFearGreedParams) {
  return useQuery({
    queryKey: ['market-fear-greed', params],
    queryFn: () => proxyGet<ApiResponse<MarketFearGreedItem>>('market/fear-greed', params as any),
  });
}

/** Returns futures market data across all tracked tokens. **Included fields:** open interest, funding rate, long/short ratio, 24h volume. Sorted by `volume_24h` by default — use `sort_by` to change. */
export function useMarketFutures(params?: MarketFuturesParams) {
  return useQuery({
    queryKey: ['market-futures', params],
    queryFn: () => proxyGet<ApiResponse<MarketFuturesItem>>('market/futures', params as any),
  });
}

/** Returns OHLC-style aggregated liquidation data for a token on a specific exchange. **Filters:** `symbol`, `exchange`, `interval`. Useful for charting liquidation volume over time. */
export function useMarketLiquidationChart(params: MarketLiquidationChartParams) {
  return useQuery({
    queryKey: ['market-liquidation-chart', params],
    queryFn: () => proxyGet<ApiResponse<MarketLiquidationChartItem>>('market/liquidation/chart', params as any),
  });
}

/** Returns liquidation breakdown by exchange. **Included fields:** total, long, and short volumes in USD. **Filters:** `symbol` and `time_range` (`1h`, `4h`, `12h`, `24h`). */
export function useMarketLiquidationExchangeList(params?: MarketLiquidationExchangeListParams) {
  return useQuery({
    queryKey: ['market-liquidation-exchange-list', params],
    queryFn: () => proxyGet<ApiResponse<MarketLiquidationExchangeListItem>>('market/liquidation/exchange-list', params as any),
  });
}

/** Returns individual large liquidation orders above a USD threshold (`min_amount`, default 10000). **Filters:** `exchange` and `symbol`. For aggregate totals and long/short breakdown by exchange, use `/market/liquidation/exchange-list`. For historical liquidation charts, use `/market/liquidation/chart`. */
export function useMarketLiquidationOrder(params?: MarketLiquidationOrderParams) {
  return useQuery({
    queryKey: ['market-liquidation-order', params],
    queryFn: () => proxyGet<ApiResponse<MarketLiquidationOrderItem>>('market/liquidation/order', params as any),
  });
}

/** Returns on-chain indicator time-series for BTC or ETH. **Available metrics:** `nupl`, `sopr`, `mvrv`, `puell-multiple`, `nvm`, `nvt`, `nvt-golden-cross`, `exchange-flows` (inflow/outflow/netflow/reserve). */
export function useMarketOnchainIndicator(params: MarketOnchainIndicatorParams) {
  return useQuery({
    queryKey: ['market-onchain-indicator', params],
    queryFn: () => proxyGet<ApiResponse<MarketOnchainIndicatorItem>>('market/onchain-indicator', params as any),
  });
}

/** Returns options market data for a `symbol`. **Included fields:** open interest, volume, put/call ratio, max pain price. */
export function useMarketOptions(params: MarketOptionsParams) {
  return useQuery({
    queryKey: ['market-options', params],
    queryFn: () => proxyGet<ApiResponse<MarketOptionsItem>>('market/options', params as any),
  });
}

/** Returns historical price data points for a token over a specified time range. **Time range options:** - Predefined: `1d`, `7d`, `14d`, `30d`, `90d`, `180d`, `365d`, `max` - Custom: use `from` / `to` (Unix seconds or `YYYY-MM-DD`) **Granularity** is automatic based on range: - `1d` → 5-minute intervals - `7d`–`90d` → hourly - `180d`+ → daily */
export function useMarketPrice(params: MarketPriceParams) {
  return useQuery({
    queryKey: ['market-price', params],
    queryFn: () => proxyGet<ApiResponse<MarketPriceItem>>('market/price', params as any),
  });
}

/** Returns a technical indicator for a trading pair on a given exchange and interval. **Modes:** - Set `from`/`to` for time-series - Omit for latest value only **Indicator-specific tuning** via `options` (e.g. `period:7`, `fast_period:8,slow_period:21,signal_period:5`, `period:10,stddev:1.5`). **Available indicators:** `rsi`, `macd`, `ema`, `sma`, `bbands`, `stoch`, `adx`, `atr`, `cci`, `obv`, `vwap`, `dmi`, `ichimoku`, `supertrend`. */
export function useMarketPriceIndicator(params: MarketPriceIndicatorParams) {
  return useQuery({
    queryKey: ['market-price-indicator', params],
    queryFn: () => proxyGet<ApiResponse<MarketPriceIndicatorItem>>('market/price-indicator', params as any),
  });
}

/** Returns tokens ranked by a specified metric. **Available metrics:** `market_cap`, `top_gainers`, `top_losers`, `volume`. **Note:** `top_gainers` and `top_losers` rank by 24h price change within the top 250 coins by market cap. For circulating supply, FDV, ATH/ATL, use `/project/detail?fields=token_info`. */
export function useInfiniteMarketRanking(params?: Omit<MarketRankingParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['market-ranking', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<MarketRankingItem>>('market/ranking', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

