// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiResponse, MarketEtfItem, MarketEtfParams, MarketFearGreedItem, MarketFearGreedParams, MarketFuturesItem, MarketFuturesParams, MarketLiquidationChartItem, MarketLiquidationChartParams, MarketLiquidationExchangeListItem, MarketLiquidationExchangeListParams, MarketLiquidationOrderItem, MarketLiquidationOrderParams, MarketOnchainIndicatorItem, MarketOnchainIndicatorParams, MarketOptionsItem, MarketOptionsParams, MarketPriceIndicatorItem, MarketPriceIndicatorParams, MarketPriceItem, MarketPriceParams, MarketRankingItem, MarketRankingParams } from '../../data/types';

/** Get daily ETF flow history for US spot ETFs — net flow (USD), token price, and per-ticker breakdown. Sorted by date descending. `symbol`: `BTC` or `ETH`. */
export function useMarketEtf(params?: MarketEtfParams) {
  return useQuery({
    queryKey: ['market-etf', params],
    queryFn: () => proxyGet<ApiResponse<MarketEtfItem>>('market/etf', params as any),
  });
}

/** Get Bitcoin Fear & Greed Index history — index value (0-100), classification label, and BTC price at each data point. Sorted newest-first. Use `from`/`to` to filter by date range. */
export function useMarketFearGreed(params?: MarketFearGreedParams) {
  return useQuery({
    queryKey: ['market-fear-greed', params],
    queryFn: () => proxyGet<ApiResponse<MarketFearGreedItem>>('market/fear-greed', params as any),
  });
}

/** Get futures market data across all tracked tokens — open interest, funding rate, long/short ratio, and 24h volume. Sort by `sort_by` (default: volume_24h). */
export function useMarketFutures(params?: MarketFuturesParams) {
  return useQuery({
    queryKey: ['market-futures', params],
    queryFn: () => proxyGet<ApiResponse<MarketFuturesItem>>('market/futures', params as any),
  });
}

/** Get OHLC-style aggregated liquidation data for a token on a specific exchange. Filter by `symbol`, `exchange`, and `interval`. Useful for charting liquidation volume over time. */
export function useMarketLiquidationChart(params?: MarketLiquidationChartParams) {
  return useQuery({
    queryKey: ['market-liquidation-chart', params],
    queryFn: () => proxyGet<ApiResponse<MarketLiquidationChartItem>>('market/liquidation-chart', params as any),
  });
}

/** Get liquidation breakdown by exchange — total, long, and short volumes in USD. Filter by `symbol` and `time_range` (`1h`, `4h`, `12h`, `24h`). */
export function useMarketLiquidationExchangeList(params?: MarketLiquidationExchangeListParams) {
  return useQuery({
    queryKey: ['market-liquidation-exchange-list', params],
    queryFn: () => proxyGet<ApiResponse<MarketLiquidationExchangeListItem>>('market/liquidation-exchange-list', params as any),
  });
}

/** Get individual large liquidation orders above a USD threshold (`min_amount`, default 10000). Filter by `exchange` and `symbol`. For aggregate totals and long/short breakdown by exchange, use `/market/liquidation/exchange-list`. For historical liquidation charts, use `/market/liquidation/chart`. */
export function useMarketLiquidationOrder(params?: MarketLiquidationOrderParams) {
  return useQuery({
    queryKey: ['market-liquidation-order', params],
    queryFn: () => proxyGet<ApiResponse<MarketLiquidationOrderItem>>('market/liquidation-order', params as any),
  });
}

/** Get on-chain indicator time-series for BTC or ETH. Metrics: `nupl`, `sopr`, `mvrv`, `puell-multiple`, `nvm`, `nvt`, `nvt-golden-cross`, `exchange-flows` (inflow/outflow/netflow/reserve). */
export function useMarketOnchainIndicator(params?: MarketOnchainIndicatorParams) {
  return useQuery({
    queryKey: ['market-onchain-indicator', params],
    queryFn: () => proxyGet<ApiResponse<MarketOnchainIndicatorItem>>('market/onchain-indicator', params as any),
  });
}

/** Get options market data — open interest, volume, put/call ratio, and max pain price for a `symbol`. */
export function useMarketOptions(params?: MarketOptionsParams) {
  return useQuery({
    queryKey: ['market-options', params],
    queryFn: () => proxyGet<ApiResponse<MarketOptionsItem>>('market/options', params as any),
  });
}

/** Get historical price data points for a token. Use `time_range` for predefined windows (`1d`, `7d`, `14d`, `30d`, `90d`, `180d`, `365d`, `max`) or `from`/`to` for a custom date range (Unix timestamp or YYYY-MM-DD). Granularity is automatic: 5-min for 1d, hourly for 7-90d, daily for 180d+. */
export function useMarketPrice(params?: MarketPriceParams) {
  return useQuery({
    queryKey: ['market-price', params],
    queryFn: () => proxyGet<ApiResponse<MarketPriceItem>>('market/price', params as any),
  });
}

/** Get a technical indicator for a trading pair on a given exchange and interval. Set `from`/`to` for time-series mode, omit for latest value. Use `options` for indicator-specific tuning (e.g. `period:7`, `fast_period:8,slow_period:21,signal_period:5`, `period:10,stddev:1.5`). Indicators: `rsi`, `macd`, `ema`, `sma`, `bbands`, `stoch`, `adx`, `atr`, `cci`, `obv`, `vwap`, `dmi`, `ichimoku`, `supertrend`. */
export function useMarketPriceIndicator(params?: MarketPriceIndicatorParams) {
  return useQuery({
    queryKey: ['market-price-indicator', params],
    queryFn: () => proxyGet<ApiResponse<MarketPriceIndicatorItem>>('market/price-indicator', params as any),
  });
}

/** List tokens ranked by metric. Available metrics: `market_cap`, `top_gainers`, `top_losers`, `volume`. Note: `top_gainers` and `top_losers` rank by 24h price change within the top 250 coins by market cap. For circulating supply, FDV, ATH/ATL, use `/project/detail?fields=token_info`. */
export function useInfiniteMarketRanking(params?: Omit<MarketRankingParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['market-ranking', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<MarketRankingItem>>('market/ranking', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

