// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiResponse, MatchingMarketDailyItem, MatchingMarketDailyParams, MatchingMarketFindItem, MatchingMarketFindParams, MatchingMarketPairsItem, MatchingMarketPairsParams } from '../../data/types';

/** Returns daily volume and open interest comparison for a specific matched market pair. Both `polymarket_condition_id` and `kalshi_market_ticker` are required. **Volume units:** Polymarket = USD, Kalshi = contracts. */
export function useInfiniteMatchingMarketDaily(params: Omit<MatchingMarketDailyParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['matching-market-daily', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<MatchingMarketDailyItem>>('prediction-market/matching/daily', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Given a Polymarket condition_id or Kalshi market_ticker, find the corresponding match on the other platform. Provide at least one of `polymarket_condition_id` or `kalshi_market_ticker`. When both are provided, results are filtered to pairs matching both (useful for verifying a specific pair). */
export function useInfiniteMatchingMarketFind(params?: Omit<MatchingMarketFindParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['matching-market-find', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<MatchingMarketFindItem>>('prediction-market/matching/find', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Returns one-to-one matched market pairs between Polymarket and Kalshi. Each pair maps a Polymarket condition_id to a Kalshi market_ticker with a confidence score. **Volume units differ:** Polymarket = USD, Kalshi = contracts ($1 binary options). **Data refresh:** seed-driven, updated periodically. */
export function useInfiniteMatchingMarketPairs(params?: Omit<MatchingMarketPairsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['matching-market-pairs', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<MatchingMarketPairsItem>>('prediction-market/matching/pairs', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

