// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiObjectResponse, ApiResponse, NewsDetailData, NewsDetailParams, NewsFeedItem, NewsFeedParams } from '../../data/types';

/** Returns the full content of a single news article by its ID (returned as `id` in feed and search results). */
export function useNewsDetail(params: NewsDetailParams) {
  return useQuery({
    queryKey: ['news-detail', params],
    queryFn: () => proxyGet<ApiObjectResponse<NewsDetailData>>('news/detail', params as any),
  });
}

/** Returns crypto news from major sources. **Filters:** `source` (enum), `project`, and time range (`from`/`to`). **Sort:** `recency` (default) or `trending`. Use the detail endpoint with article `id` for full content. */
export function useInfiniteNewsFeed(params?: Omit<NewsFeedParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['news-feed', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<NewsFeedItem>>('news/feed', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

