// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiObjectResponse, ApiResponse, OnchainBridgeRankingItem, OnchainBridgeRankingParams, OnchainGasPriceData, OnchainGasPriceParams, OnchainSchemaItem, OnchainSqlItem, OnchainSqlParams, OnchainStructuredQueryItem, OnchainStructuredQueryParams, OnchainTxItem, OnchainTxParams, OnchainYieldRankingItem, OnchainYieldRankingParams } from '../../data/types';

/** List bridge protocols ranked by total USD volume over a time range. */
export function useInfiniteOnchainBridgeRanking(params?: Omit<OnchainBridgeRankingParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['onchain-bridge-ranking', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<OnchainBridgeRankingItem>>('onchain/bridge-ranking', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get the current gas price for an EVM chain via `eth_gasPrice` JSON-RPC. Returns gas price in both wei (raw) and Gwei (human-readable). **Supported chains:** `ethereum`, `polygon`, `bsc`, `arbitrum`, `optimism`, `base`, `avalanche`, `fantom`, `linea`, `cyber`. */
export function useOnchainGasPrice(params?: OnchainGasPriceParams) {
  return useQuery({
    queryKey: ['onchain-gas-price', params],
    queryFn: () => proxyGet<ApiObjectResponse<OnchainGasPriceData>>('onchain/gas-price', params as any),
  });
}

/** Execute a structured JSON query on blockchain data. No raw SQL needed — specify source, fields, filters, sort, and pagination. All tables live in the **agent** database. Use `GET /v1/onchain/schema` to discover available tables and their columns. - Source format: `agent.<table_name>` like `agent.ethereum_transactions` or `agent.ethereum_dex_trades` - Max 10,000 rows (default 20), 30s timeout. - **Always filter on block_date** — it is the partition key. Without it, queries scan billions of rows and will timeout. - **Data refresh:** ~24 hours. */
export function useOnchainStructuredQuery(params: OnchainStructuredQueryParams) {
  return useQuery({
    queryKey: ['onchain-structured-query', params],
    queryFn: () => proxyPost<ApiResponse<OnchainStructuredQueryItem>>('onchain/structured-query', params),
  });
}

/** Get table metadata — database, table, column names, types, and comments for all available on-chain databases. */
export function useOnchainSchema() {
  return useQuery({
    queryKey: ['onchain-schema'],
    queryFn: () => proxyGet<ApiResponse<OnchainSchemaItem>>('onchain/schema'),
  });
}

/** Execute a raw SQL SELECT query against blockchain data. All tables live in the **agent** database. Use `GET /v1/onchain/schema` to discover available tables and their columns before writing queries. */
export function useOnchainSql(params: OnchainSqlParams) {
  return useQuery({
    queryKey: ['onchain-sql', params],
    queryFn: () => proxyPost<ApiResponse<OnchainSqlItem>>('onchain/sql', params),
  });
}

/** Get transaction details by hash. All numeric fields are hex-encoded — use parseInt(hex, 16) to convert. **Supported chains:** `ethereum`, `polygon`, `bsc`, `arbitrum`, `optimism`, `base`, `avalanche`, `fantom`, `linea`, `cyber`. Returns 404 if the transaction is not found. */
export function useOnchainTx(params?: OnchainTxParams) {
  return useQuery({
    queryKey: ['onchain-tx', params],
    queryFn: () => proxyGet<ApiResponse<OnchainTxItem>>('onchain/tx', params as any),
  });
}

/** List DeFi yield pools ranked by APY or TVL. Returns the latest snapshot. Filter by protocol. */
export function useInfiniteOnchainYieldRanking(params?: Omit<OnchainYieldRankingParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['onchain-yield-ranking', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<OnchainYieldRankingItem>>('onchain/yield-ranking', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

