// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiResponse, PolymarketActivityItem, PolymarketActivityParams, PolymarketEventsItem, PolymarketEventsParams, PolymarketMarketsItem, PolymarketMarketsParams, PolymarketOpenInterestItem, PolymarketOpenInterestParams, PolymarketPositionsItem, PolymarketPositionsParams, PolymarketPricesItem, PolymarketPricesParams, PolymarketRankingItem, PolymarketRankingParams, PolymarketTradesItem, PolymarketTradesParams, PolymarketVolumesItem, PolymarketVolumesParams } from '../../data/types';

/** Get trade and redemption activity for a Polymarket wallet. Data refresh: ~30 minutes */
export function useInfinitePolymarketActivity(params: Omit<PolymarketActivityParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['polymarket-activity', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<PolymarketActivityItem>>('prediction-market/polymarket/activity', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get Polymarket events with nested markets, optionally filtered by `event_slug`. Each event includes aggregated status, volume, and a list of markets with `side_a`/`side_b` outcomes. Data refresh: ~30 minutes */
export function useInfinitePolymarketEvents(params: Omit<PolymarketEventsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['polymarket-events', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<PolymarketEventsItem>>('prediction-market/polymarket/events', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get Polymarket markets, optionally filtered by `market_slug`. Each market includes `side_a` and `side_b` outcomes. Current prices are available via `/polymarket/prices` using the `condition_id`. Data refresh: ~30 minutes */
export function useInfinitePolymarketMarkets(params: Omit<PolymarketMarketsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['polymarket-markets', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<PolymarketMarketsItem>>('prediction-market/polymarket/markets', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get daily open interest history for a Polymarket market. Data refresh: ~30 minutes */
export function useInfinitePolymarketOpenInterest(params: Omit<PolymarketOpenInterestParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['polymarket-open-interest', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<PolymarketOpenInterestItem>>('prediction-market/polymarket/open-interest', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get wallet positions on Polymarket markets. Data refresh: ~30 minutes */
export function useInfinitePolymarketPositions(params: Omit<PolymarketPositionsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['polymarket-positions', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<PolymarketPositionsItem>>('prediction-market/polymarket/positions', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get aggregated price history for a Polymarket market. Use `interval=latest` for the most recent price snapshot. Data refresh: ~30 minutes */
export function useInfinitePolymarketPrices(params: Omit<PolymarketPricesParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['polymarket-prices', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<PolymarketPricesItem>>('prediction-market/polymarket/prices', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get top-ranked Polymarket markets by `volume_24h`, `volume_7d`, `open_interest`, or `trade_count`. Filter by `status` and `end_before`. Data refresh: ~30 minutes */
export function useInfinitePolymarketRanking(params?: Omit<PolymarketRankingParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['polymarket-ranking', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<PolymarketRankingItem>>('prediction-market/polymarket/ranking', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get paginated trade records for a Polymarket market or wallet. Filter by `condition_id` (market) or `address` (wallet), plus `outcome_label`, `min_amount`, and date range. At least one of `condition_id` or `address` is required. Sort by `newest`, `oldest`, or `largest`. Data refresh: ~30 minutes */
export function useInfinitePolymarketTrades(params?: Omit<PolymarketTradesParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['polymarket-trades', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<PolymarketTradesItem>>('prediction-market/polymarket/trades', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get trading volume and trade count history for a Polymarket market. Data refresh: ~30 minutes */
export function useInfinitePolymarketVolumes(params: Omit<PolymarketVolumesParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['polymarket-volumes', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<PolymarketVolumesItem>>('prediction-market/polymarket/volumes', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

