// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiCursorResponse, ApiResponse, SearchAirdropItem, SearchAirdropParams, SearchEventsItem, SearchEventsParams, SearchFundItem, SearchFundParams, SearchKalshiItem, SearchKalshiParams, SearchNewsItem, SearchNewsParams, SearchPolymarketItem, SearchPolymarketParams, SearchProjectItem, SearchProjectParams, SearchSocialPeopleItem, SearchSocialPeopleParams, SearchSocialPostsItem, SearchSocialPostsParams, SearchWalletItem, SearchWalletParams, SearchWebItem, SearchWebParams } from '../../data/types';

/** Searches and filters airdrop opportunities. **Filters:** keyword, status, reward type, task type. Returns paginated results with optional task details. */
export function useInfiniteSearchAirdrop(params?: Omit<SearchAirdropParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-airdrop', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchAirdropItem>>('search/airdrop', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Searches project events by keyword, optionally filtered by `type`. **Valid types:** `launch`, `upgrade`, `partnership`, `news`, `airdrop`, `listing`, `twitter`. **Lookup:** by UUID (`id`) or name (`q`). Returns 404 if the project is not found. */
export function useInfiniteSearchEvents(params?: Omit<SearchEventsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-events', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchEventsItem>>('search/events', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Searches funds by keyword. **Included fields:** name, tier, type, logo, top invested projects. */
export function useInfiniteSearchFund(params: Omit<SearchFundParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-fund', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchFundItem>>('search/fund', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Searches Kalshi events by keyword and/or category. **Filters:** - Keyword matching event title, subtitle, or market title - Category At least one of `q` or `category` is required. Returns events with nested markets. **Data refresh:** ~30 minutes */
export function useInfiniteSearchKalshi(params?: Omit<SearchKalshiParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-kalshi', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchKalshiItem>>('search/kalshi', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Searches crypto news articles by keyword. Returns top 10 results ranked by relevance with highlighted matching fragments. */
export function useInfiniteSearchNews(params: Omit<SearchNewsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-news', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchNewsItem>>('search/news', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Searches Polymarket events by keyword, tags, and/or category. **Filters:** - Keyword matching market question, event title, or description - Comma-separated tag labels - Surf-curated category At least one of `q`, `tags`, or `category` is required. Returns events with nested markets ranked by volume. **Data refresh:** ~30 minutes */
export function useInfiniteSearchPolymarket(params?: Omit<SearchPolymarketParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-polymarket', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchPolymarketItem>>('search/polymarket', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Searches crypto projects by keyword. **Included fields:** name, description, chains, logo. */
export function useInfiniteSearchProject(params: Omit<SearchProjectParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-project', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchProjectItem>>('search/project', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Searches X (Twitter) users by keyword. **Included fields:** handle, display name, bio, follower count, avatar. */
export function useInfiniteSearchSocialPeople(params: Omit<SearchSocialPeopleParams, 'cursor'>) {
  return useInfiniteQuery({
    queryKey: ['search-social-people', params],
    queryFn: ({ pageParam }) => proxyGet<ApiCursorResponse<SearchSocialPeopleItem>>('search/social/people', { ...params!, cursor: pageParam || undefined }),
    initialPageParam: '',
    getNextPageParam: (last) => last?.meta?.has_more ? last.meta.next_cursor : undefined,
  });
}

/** Searches X (Twitter) posts by keyword or `from:handle` syntax. **Included fields:** author, content, engagement metrics, timestamp. **Pagination:** check `meta.has_more`; if true, pass `meta.next_cursor` as the `cursor` query parameter in the next request. */
export function useInfiniteSearchSocialPosts(params: Omit<SearchSocialPostsParams, 'cursor'>) {
  return useInfiniteQuery({
    queryKey: ['search-social-posts', params],
    queryFn: ({ pageParam }) => proxyGet<ApiCursorResponse<SearchSocialPostsItem>>('search/social/posts', { ...params!, cursor: pageParam || undefined }),
    initialPageParam: '',
    getNextPageParam: (last) => last?.meta?.has_more ? last.meta.next_cursor : undefined,
  });
}

/** Searches wallets by ENS name, address label, or address prefix. Returns matching wallet addresses with entity labels. */
export function useInfiniteSearchWallet(params: Omit<SearchWalletParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-wallet', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchWalletItem>>('search/wallet', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Searches web pages, articles, and content by keyword. **Filters:** domain via `site` (e.g. `coindesk.com`). **Included fields:** titles, URLs, content snippets. */
export function useInfiniteSearchWeb(params: Omit<SearchWebParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-web', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchWebItem>>('search/web', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

