// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiCursorResponse, ApiResponse, SearchAirdropItem, SearchAirdropParams, SearchEventsItem, SearchEventsParams, SearchFundItem, SearchFundParams, SearchKalshiItem, SearchKalshiParams, SearchNewsItem, SearchNewsParams, SearchPolymarketItem, SearchPolymarketParams, SearchProjectItem, SearchProjectParams, SearchSocialPeopleItem, SearchSocialPeopleParams, SearchSocialPostsItem, SearchSocialPostsParams, SearchWalletItem, SearchWalletParams, SearchWebItem, SearchWebParams } from '../../data/types';

/** Search and filter airdrop opportunities by keyword, status, reward type, and task type. Returns paginated results with optional task details. */
export function useInfiniteSearchAirdrop(params?: Omit<SearchAirdropParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-airdrop', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchAirdropItem>>('search/airdrop', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Search project events by keyword, optionally filtered by `type`. Valid types: `launch`, `upgrade`, `partnership`, `news`, `airdrop`, `listing`, `twitter`. Lookup by UUID (`id`) or name (`q`). Returns 404 if the project is not found. */
export function useInfiniteSearchEvents(params?: Omit<SearchEventsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-events', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchEventsItem>>('search/events', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Search funds by keyword. Returns matching funds with name, tier, type, logo, and top invested projects. */
export function useInfiniteSearchFund(params?: Omit<SearchFundParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-fund', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchFundItem>>('search/fund', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Search Kalshi events by keyword and/or category. Filter by keyword matching event title, subtitle, or market title; or by category. At least one of `q` or `category` is required. Returns events with nested markets. Data refresh: ~30 minutes */
export function useInfiniteSearchKalshi(params?: Omit<SearchKalshiParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-kalshi', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchKalshiItem>>('search/kalshi', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Search crypto news articles by keyword. Returns top 10 results ranked by relevance with highlighted matching fragments. */
export function useSearchNews(params?: SearchNewsParams) {
  return useQuery({
    queryKey: ['search-news', params],
    queryFn: () => proxyGet<ApiResponse<SearchNewsItem>>('search/news', params as any),
  });
}

/** Search Polymarket events by keyword, tags, and/or category. Filter by keyword matching market question, event title, or description; by comma-separated tag labels; or by Surf-curated category. At least one of `q`, `tags`, or `category` is required. Returns events with nested markets ranked by volume. Data refresh: ~30 minutes */
export function useInfiniteSearchPolymarket(params?: Omit<SearchPolymarketParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-polymarket', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchPolymarketItem>>('search/polymarket', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Search crypto projects by keyword. Returns matching projects with name, description, chains, and logo. */
export function useInfiniteSearchProject(params?: Omit<SearchProjectParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-project', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchProjectItem>>('search/project', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Search X (Twitter) users by keyword. Returns user profiles with handle, display name, bio, follower count, and avatar. */
export function useInfiniteSearchSocialPeople(params?: Omit<SearchSocialPeopleParams, 'cursor'>) {
  return useInfiniteQuery({
    queryKey: ['search-social-people', params],
    queryFn: ({ pageParam }) => proxyGet<ApiCursorResponse<SearchSocialPeopleItem>>('search/social-people', { ...params!, cursor: pageParam || undefined }),
    initialPageParam: '',
    getNextPageParam: (last) => last?.meta?.has_more ? last.meta.next_cursor : undefined,
  });
}

/** Search X (Twitter) posts by keyword or `from:handle` syntax. Returns posts with author, content, engagement metrics, and timestamp. To load more results, check `meta.has_more`; if true, pass `meta.next_cursor` as the `cursor` query parameter in the next request. */
export function useInfiniteSearchSocialPosts(params?: Omit<SearchSocialPostsParams, 'cursor'>) {
  return useInfiniteQuery({
    queryKey: ['search-social-posts', params],
    queryFn: ({ pageParam }) => proxyGet<ApiCursorResponse<SearchSocialPostsItem>>('search/social-posts', { ...params!, cursor: pageParam || undefined }),
    initialPageParam: '',
    getNextPageParam: (last) => last?.meta?.has_more ? last.meta.next_cursor : undefined,
  });
}

/** Search wallets by ENS name, address label, or address prefix. Returns matching wallet addresses with entity labels. */
export function useInfiniteSearchWallet(params?: Omit<SearchWalletParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-wallet', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchWalletItem>>('search/wallet', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Search web pages, articles, and content by keyword. Filter by domain with `site` like `coindesk.com`. Returns titles, URLs, and content snippets. */
export function useInfiniteSearchWeb(params?: Omit<SearchWebParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['search-web', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SearchWebItem>>('search/web', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

