// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiCursorResponse, ApiObjectResponse, ApiResponse, SocialDetailData, SocialDetailParams, SocialMindshareItem, SocialMindshareParams, SocialRankingItem, SocialRankingParams, SocialSmartFollowersHistoryItem, SocialSmartFollowersHistoryParams, SocialTweetRepliesItem, SocialTweetRepliesParams, SocialTweetsItem, SocialTweetsParams, SocialUserData, SocialUserFollowersItem, SocialUserFollowersParams, SocialUserFollowingItem, SocialUserFollowingParams, SocialUserParams, SocialUserPostsItem, SocialUserPostsParams, SocialUserRepliesItem, SocialUserRepliesParams } from '../../data/types';

/** Returns a **point-in-time snapshot** of social analytics for a project. **Available fields** (via `fields`): `sentiment`, `follower_geo`, `smart_followers`. **Lookup:** by X account ID (`x_id`) or project name (`q`, e.g. `uniswap`, `solana`). The `q` parameter must be a crypto project name, not a personal Twitter handle. Returns 404 if the project has no linked Twitter account. For sentiment **trends over time**, use `/social/mindshare` instead. */
export function useSocialDetail(params?: SocialDetailParams) {
  return useQuery({
    queryKey: ['social-detail', params],
    queryFn: () => proxyGet<ApiObjectResponse<SocialDetailData>>('social/detail', params as any),
  });
}

/** Returns mindshare (social view count) **time-series trend** for a project, aggregated by `interval`. **Intervals:** `5m`, `1h`, `1d`, `7d`. **Filters:** date range with `from`/`to` (Unix seconds). Lookup by name (`q`). Use this for sentiment **trends**, mindshare **over time**, or social momentum changes. For a **point-in-time snapshot** of social analytics (sentiment score, follower geo, smart followers), use `/social/detail` instead. */
export function useInfiniteSocialMindshare(params: Omit<SocialMindshareParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['social-mindshare', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SocialMindshareItem>>('social/mindshare', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Returns top crypto projects ranked by mindshare (social view count), refreshed every 5 minutes. **Filters:** - `tag` — scope to a category (e.g. `dex`, `l1`, `meme`) - `time_range` — ranking window (`24h`, `48h`, `7d`, `30d`) Supports `limit`/`offset` pagination. */
export function useInfiniteSocialRanking(params?: Omit<SocialRankingParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['social-ranking', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SocialRankingItem>>('social/ranking', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Returns smart follower count time-series for a project, sorted by date descending. **Lookup:** by X account ID (`x_id`) or project name (`q`). The `q` parameter must be a project name (e.g. `uniswap`, `ethereum`), not a personal X handle — use `x_id` for individual accounts. Returns 404 if the project has no linked X account. */
export function useInfiniteSocialSmartFollowersHistory(params?: Omit<SocialSmartFollowersHistoryParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['social-smart-followers-history', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SocialSmartFollowersHistoryItem>>('social/smart-followers/history', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Returns replies/comments on a specific tweet. **Lookup:** by `tweet_id`. */
export function useInfiniteSocialTweetReplies(params: Omit<SocialTweetRepliesParams, 'cursor'>) {
  return useInfiniteQuery({
    queryKey: ['social-tweet-replies', params],
    queryFn: ({ pageParam }) => proxyGet<ApiCursorResponse<SocialTweetRepliesItem>>('social/tweet/replies', { ...params!, cursor: pageParam || undefined }),
    initialPageParam: '',
    getNextPageParam: (last) => last?.meta?.has_more ? last.meta.next_cursor : undefined,
  });
}

/** Returns X (Twitter) posts by numeric post ID strings. Pass up to 100 comma-separated IDs via the `ids` query parameter. */
export function useInfiniteSocialTweets(params: Omit<SocialTweetsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['social-tweets', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<SocialTweetsItem>>('social/tweets', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Returns an X (Twitter) user profile. **Included fields:** display name, follower count, following count, and bio. **Lookup:** by `handle` (without @). */
export function useSocialUser(params: SocialUserParams) {
  return useQuery({
    queryKey: ['social-user', params],
    queryFn: () => proxyGet<ApiObjectResponse<SocialUserData>>('social/user', params as any),
  });
}

/** Returns a list of followers for the specified handle on X (Twitter). **Lookup:** by `handle` (without @). */
export function useInfiniteSocialUserFollowers(params: Omit<SocialUserFollowersParams, 'cursor'>) {
  return useInfiniteQuery({
    queryKey: ['social-user-followers', params],
    queryFn: ({ pageParam }) => proxyGet<ApiCursorResponse<SocialUserFollowersItem>>('social/user/followers', { ...params!, cursor: pageParam || undefined }),
    initialPageParam: '',
    getNextPageParam: (last) => last?.meta?.has_more ? last.meta.next_cursor : undefined,
  });
}

/** Returns a list of users that the specified handle follows on X (Twitter). **Lookup:** by `handle` (without @). */
export function useInfiniteSocialUserFollowing(params: Omit<SocialUserFollowingParams, 'cursor'>) {
  return useInfiniteQuery({
    queryKey: ['social-user-following', params],
    queryFn: ({ pageParam }) => proxyGet<ApiCursorResponse<SocialUserFollowingItem>>('social/user/following', { ...params!, cursor: pageParam || undefined }),
    initialPageParam: '',
    getNextPageParam: (last) => last?.meta?.has_more ? last.meta.next_cursor : undefined,
  });
}

/** Returns recent X (Twitter) posts by a specific user, ordered by recency. **Lookup:** by `handle` (without @). Use `filter=original` to exclude retweets. **Pagination:** check `meta.has_more`; if true, pass `meta.next_cursor` as the `cursor` query parameter in the next request. */
export function useInfiniteSocialUserPosts(params: Omit<SocialUserPostsParams, 'cursor'>) {
  return useInfiniteQuery({
    queryKey: ['social-user-posts', params],
    queryFn: ({ pageParam }) => proxyGet<ApiCursorResponse<SocialUserPostsItem>>('social/user/posts', { ...params!, cursor: pageParam || undefined }),
    initialPageParam: '',
    getNextPageParam: (last) => last?.meta?.has_more ? last.meta.next_cursor : undefined,
  });
}

/** Returns recent replies by the specified handle on X (Twitter). **Lookup:** by `handle` (without @). */
export function useInfiniteSocialUserReplies(params: Omit<SocialUserRepliesParams, 'cursor'>) {
  return useInfiniteQuery({
    queryKey: ['social-user-replies', params],
    queryFn: ({ pageParam }) => proxyGet<ApiCursorResponse<SocialUserRepliesItem>>('social/user/replies', { ...params!, cursor: pageParam || undefined }),
    initialPageParam: '',
    getNextPageParam: (last) => last?.meta?.has_more ? last.meta.next_cursor : undefined,
  });
}

