// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiResponse, TokenDexTradesItem, TokenDexTradesParams, TokenHoldersItem, TokenHoldersParams, TokenTokenomicsItem, TokenTokenomicsParams, TokenTransfersItem, TokenTransfersParams } from '../../data/types';

/** Get recent DEX swap events for a token contract address. Covers DEXes like `uniswap`, `sushiswap`, `curve`, and `balancer` on `ethereum` and `base`. Returns trading pair, amounts, USD value, and taker address. Data refresh: ~24 hours · Chain: Ethereum, Base */
export function useInfiniteTokenDexTrades(params: Omit<TokenDexTradesParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['token-dex-trades', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<TokenDexTradesItem>>('token/dex-trades', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get top token holders for a contract address — wallet address, balance, and percentage. Lookup by `address` and `chain`. Supports EVM chains and Solana. */
export function useInfiniteTokenHolders(params: Omit<TokenHoldersParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['token-holders', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<TokenHoldersItem>>('token/holders', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get token unlock time-series — unlock events with amounts and allocation breakdowns. Lookup by project UUID (`id`) or token `symbol`. Filter by date range with `from`/`to`. Defaults to the current calendar month when omitted. Returns 404 if no token found. */
export function useInfiniteTokenTokenomics(params?: Omit<TokenTokenomicsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['token-tokenomics', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<TokenTokenomicsItem>>('token/tokenomics', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get recent transfer events **for a specific token** (ERC-20/TRC-20 contract). Pass the **token contract address** in `address` — returns every on-chain transfer of that token regardless of sender/receiver. Each record includes sender, receiver, raw amount, and block timestamp. Use this to analyze a token's on-chain activity (e.g. large movements, distribution patterns). Lookup: `address` (token contract) + `chain`. Sort by `asc` or `desc`. Data refresh: ~24 hours · Chain: Ethereum, Base, TRON (Solana uses a different source with no delay) */
export function useInfiniteTokenTransfers(params: Omit<TokenTransfersParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['token-transfers', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<TokenTransfersItem>>('token/transfers', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

