// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiResponse, V2KalshiOrderbooksItem, V2KalshiOrderbooksParams, V2PolymarketCandlesticksItem, V2PolymarketCandlesticksParams, V2PolymarketOrderbooksItem, V2PolymarketOrderbooksParams, V2PolymarketVolumeChartItem, V2PolymarketVolumeChartParams, V2PolymarketVolumeTimeseriesItem, V2PolymarketVolumeTimeseriesParams } from '../../data/types';

/** Historical orderbook snapshots for a Kalshi market. Returns yes-side bid/ask levels. Timestamps in milliseconds, prices in cents. Data refresh: ~5 minutes */
export function useV2KalshiOrderbooks(params: V2KalshiOrderbooksParams) {
  return useQuery({
    queryKey: ['v2-kalshi-orderbooks', params],
    queryFn: () => proxyGet<ApiResponse<V2KalshiOrderbooksItem>>('gateway/v2/kalshi/orderbooks', params as any),
  });
}

/** OHLCV candlestick data for a Polymarket market. Prices normalized to YES side. Data refresh: ~30 minutes */
export function useV2PolymarketCandlesticks(params?: V2PolymarketCandlesticksParams) {
  return useQuery({
    queryKey: ['v2-polymarket-candlesticks', params],
    queryFn: () => proxyGet<ApiResponse<V2PolymarketCandlesticksItem>>('gateway/v2/polymarket/candlesticks/{condition_id}', params as any),
  });
}

/** Cumulative volume time series for a Polymarket token. Data refresh: ~30 minutes */
export function useV2PolymarketVolumeTimeseries(params?: V2PolymarketVolumeTimeseriesParams) {
  return useQuery({
    queryKey: ['v2-polymarket-volume-timeseries', params],
    queryFn: () => proxyGet<ApiResponse<V2PolymarketVolumeTimeseriesItem>>('gateway/v2/polymarket/markets/{token_id}/volume', params as any),
  });
}

/** Historical orderbook snapshots for a Polymarket token. Returns raw bid/ask depth levels. Timestamps in milliseconds. Data refresh: ~5 minutes */
export function useV2PolymarketOrderbooks(params: V2PolymarketOrderbooksParams) {
  return useQuery({
    queryKey: ['v2-polymarket-orderbooks', params],
    queryFn: () => proxyGet<ApiResponse<V2PolymarketOrderbooksItem>>('gateway/v2/polymarket/orderbooks', params as any),
  });
}

/** Volume breakdown by outcome (YES/NO) for a Polymarket market. Data refresh: ~30 minutes */
export function useV2PolymarketVolumeChart(params?: V2PolymarketVolumeChartParams) {
  return useQuery({
    queryKey: ['v2-polymarket-volume-chart', params],
    queryFn: () => proxyGet<ApiResponse<V2PolymarketVolumeChartItem>>('gateway/v2/polymarket/volume-chart/{condition_id}', params as any),
  });
}

