// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiObjectResponse, ApiResponse, WalletDetailData, WalletDetailParams, WalletHistoryItem, WalletHistoryParams, WalletLabelsBatchItem, WalletLabelsBatchParams, WalletNetWorthItem, WalletNetWorthParams, WalletProtocolsItem, WalletProtocolsParams, WalletTransfersItem, WalletTransfersParams } from '../../data/types';

/** Get multiple wallet sub-resources in a single request. Lookup by `address`. Use `fields` to select: `balance`, `tokens`, `labels`, `nft`. Partial failures return available fields with per-field error info. Returns 422 if `fields` is invalid. */
export function useWalletDetail(params?: WalletDetailParams) {
  return useQuery({
    queryKey: ['wallet-detail', params],
    queryFn: () => proxyGet<ApiObjectResponse<WalletDetailData>>('wallet/detail', params as any),
  });
}

/** Get full transaction history for a wallet — swaps, transfers, and contract interactions. Lookup by `address`. Filter by `chain` — supports `ethereum`, `polygon`, `bsc`, `arbitrum`, `optimism`, `avalanche`, `fantom`, `base`. */
export function useInfiniteWalletHistory(params?: Omit<WalletHistoryParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['wallet-history', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<WalletHistoryItem>>('wallet/history', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get entity labels for multiple wallet addresses. Pass up to 100 comma-separated addresses via the `addresses` query parameter. Returns entity name, type, and labels per address. */
export function useWalletLabelsBatch(params?: WalletLabelsBatchParams) {
  return useQuery({
    queryKey: ['wallet-labels-batch', params],
    queryFn: () => proxyGet<ApiResponse<WalletLabelsBatchItem>>('wallet/labels-batch', params as any),
  });
}

/** Get a time-series of the wallet's total net worth in USD. Returns ~288 data points at 5-minute intervals covering the last 24 hours. Fixed window — no custom time range supported. */
export function useWalletNetWorth(params?: WalletNetWorthParams) {
  return useQuery({
    queryKey: ['wallet-net-worth', params],
    queryFn: () => proxyGet<ApiResponse<WalletNetWorthItem>>('wallet/net-worth', params as any),
  });
}

/** Get all DeFi protocol positions for a wallet — lending, staking, LP, and farming with token breakdowns and USD values. Lookup by `address`. */
export function useInfiniteWalletProtocols(params?: Omit<WalletProtocolsParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['wallet-protocols', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<WalletProtocolsItem>>('wallet/protocols', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

/** Get recent token transfers **sent or received by a wallet**. Pass the **wallet address** in `address` — returns all ERC-20/SPL token transfers where this wallet is the sender or receiver. Each record includes token contract, counterparty, raw amount, and block timestamp. Use this to audit a wallet's token flow (e.g. inflows, outflows, airdrop receipts). Lookup: `address` (wallet, raw 0x hex or base58 — ENS not supported). Filter by `chain` — supports `ethereum`, `base`, `solana`. Data refresh: ~24 hours · Chain: Ethereum, Base (Solana uses a different source with no delay) */
export function useInfiniteWalletTransfers(params?: Omit<WalletTransfersParams, 'offset'>) {
  return useInfiniteQuery({
    queryKey: ['wallet-transfers', params],
    queryFn: ({ pageParam = 0 }) => proxyGet<ApiResponse<WalletTransfersItem>>('wallet/transfers', { ...params!, offset: String(pageParam) }),
    initialPageParam: 0,
    getNextPageParam: (last) => {
      const m = last?.meta;
      if (!m?.total || !m?.limit) return undefined;
      const next = (m.offset ?? 0) + m.limit;
      return next < m.total ? next : undefined;
    },
  });
}

