// Auto-generated by gen_sdk.py — do not edit.

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { proxyGet, proxyPost } from '../fetch';
import type { ApiObjectResponse, WebFetchData, WebFetchParams } from '../../data/types';

/** Fetches a web page and converts it to clean, LLM-friendly markdown. **Options:** - `target_selector` — extract specific page sections - `remove_selector` — strip unwanted elements Returns 400 if the URL is invalid or unreachable. */
export function useWebFetch(params: WebFetchParams) {
  return useQuery({
    queryKey: ['web-fetch', params],
    queryFn: () => proxyGet<ApiObjectResponse<WebFetchData>>('web/fetch', params as any),
  });
}

