// Auto-generated by gen_sdk.py — do not edit.

import { get, post } from '../client';
import type { ApiResponse, KalshiEventsItem, KalshiEventsParams, KalshiMarketsItem, KalshiMarketsParams, KalshiOpenInterestItem, KalshiOpenInterestParams, KalshiOrderbooksItem, KalshiOrderbooksParams, KalshiPricesItem, KalshiPricesParams, KalshiTradesItem, KalshiTradesParams, KalshiVolumesItem, KalshiVolumesParams } from '../types';

export const kalshi = {
  /** Returns Kalshi events with nested markets, optionally filtered by `event_ticker`. Each event includes market count and a list of markets. **Data refresh:** ~30 minutes */
  events: (params?: KalshiEventsParams): Promise<ApiResponse<KalshiEventsItem>> =>
    get('prediction-market/kalshi/events', params as any),

  /** Returns Kalshi markets, optionally filtered by `market_ticker`. Each market includes price, volume, and status. **Data refresh:** ~30 minutes */
  markets: (params?: KalshiMarketsParams): Promise<ApiResponse<KalshiMarketsItem>> =>
    get('prediction-market/kalshi/markets', params as any),

  /** Daily open interest time series for a Kalshi market. **Data refresh:** ~30 minutes */
  open_interest: (params: KalshiOpenInterestParams): Promise<ApiResponse<KalshiOpenInterestItem>> =>
    get('prediction-market/kalshi/open-interest', params as any),

  /** Historical orderbook snapshots for a Kalshi market. Returns yes-side bid/ask levels. Timestamps in milliseconds, prices in cents. Data refresh: ~5 minutes */
  orderbooks: (params: KalshiOrderbooksParams): Promise<ApiResponse<KalshiOrderbooksItem>> =>
    get('prediction-market/kalshi/orderbooks', params as any),

  /** Price time series for a Kalshi market with daily or hourly OHLC data, or latest price from recent trades. **Data refresh:** ~30 minutes */
  prices: (params: KalshiPricesParams): Promise<ApiResponse<KalshiPricesItem>> =>
    get('prediction-market/kalshi/prices', params as any),

  /** Returns individual trade records for a Kalshi market. **Filters:** `taker_side`, `min_contracts`, and date range. **Sort:** `timestamp` or `num_contracts`. **Data refresh:** real-time */
  trades: (params: KalshiTradesParams): Promise<ApiResponse<KalshiTradesItem>> =>
    get('prediction-market/kalshi/trades', params as any),

  /** Daily trading volume time series for a Kalshi market. **Data refresh:** ~30 minutes */
  volumes: (params: KalshiVolumesParams): Promise<ApiResponse<KalshiVolumesItem>> =>
    get('prediction-market/kalshi/volumes', params as any),

};

