// Auto-generated by gen_sdk.py — do not edit.

import { get, post } from '../client';
import type { ApiResponse, MatchingMarketDailyItem, MatchingMarketDailyParams, MatchingMarketFindItem, MatchingMarketFindParams, MatchingMarketPairsItem, MatchingMarketPairsParams } from '../types';

export const matching = {
  /** Returns daily volume and open interest comparison for a specific matched market pair. Both `polymarket_condition_id` and `kalshi_market_ticker` are required. **Volume units:** Polymarket = USD, Kalshi = contracts. */
  market_daily: (params: MatchingMarketDailyParams): Promise<ApiResponse<MatchingMarketDailyItem>> =>
    get('prediction-market/matching/daily', params as any),

  /** Given a Polymarket condition_id or Kalshi market_ticker, find the corresponding match on the other platform. Provide at least one of `polymarket_condition_id` or `kalshi_market_ticker`. When both are provided, results are filtered to pairs matching both (useful for verifying a specific pair). */
  market_find: (params?: MatchingMarketFindParams): Promise<ApiResponse<MatchingMarketFindItem>> =>
    get('prediction-market/matching/find', params as any),

  /** Returns one-to-one matched market pairs between Polymarket and Kalshi. Each pair maps a Polymarket condition_id to a Kalshi market_ticker with a confidence score. **Volume units differ:** Polymarket = USD, Kalshi = contracts ($1 binary options). **Data refresh:** seed-driven, updated periodically. */
  market_pairs: (params?: MatchingMarketPairsParams): Promise<ApiResponse<MatchingMarketPairsItem>> =>
    get('prediction-market/matching/pairs', params as any),

};

