// Auto-generated by gen_sdk.py — do not edit.

import { get, post } from '../client';
import type { ApiResponse, MatchingMarketDailyItem, MatchingMarketDailyParams, MatchingMarketPairsItem, MatchingMarketPairsParams } from '../types';

export const matching = {
  /** Returns daily volume and open interest comparison for a specific Polymarket <> Kalshi matched pair. Both `polymarket_condition_id` and `kalshi_market_ticker` are required. Use `matching-market-pairs` to discover matched pairs first. **Volume units:** Polymarket = USD, Kalshi = contracts. */
  market_daily: (params: MatchingMarketDailyParams): Promise<ApiResponse<MatchingMarketDailyItem>> =>
    get('prediction-market/matching/daily', params as any),

  /** Cross-platform prediction market pair matcher — finds the same event listed on both Polymarket and Kalshi, with live price spread data. This is prediction-market only (Polymarket and Kalshi). For crypto exchange markets, use `exchange-markets`. Filter by category, match type, confidence score, or look up a specific market's cross-platform counterpart via `polymarket_condition_id` or `kalshi_market_ticker`. Each pair includes current prices and spread percentage for arbitrage analysis. Sort by `spread_pct` to find the widest spreads. **Data refresh:** ~5 minutes */
  market_pairs: (params?: MatchingMarketPairsParams): Promise<ApiResponse<MatchingMarketPairsItem>> =>
    get('prediction-market/matching/pairs', params as any),

};

