// Auto-generated by gen_sdk.py — do not edit.

import { get, post } from '../client';
import type { ApiResponse, PolymarketEventsItem, PolymarketEventsParams, PolymarketLeaderboardItem, PolymarketLeaderboardParams, PolymarketMarketsItem, PolymarketMarketsParams, PolymarketOpenInterestItem, PolymarketOpenInterestParams, PolymarketOrderbooksItem, PolymarketOrderbooksParams, PolymarketPositionsItem, PolymarketPositionsParams, PolymarketPriceOhlcvItem, PolymarketPriceOhlcvParams, PolymarketPricesItem, PolymarketPricesParams, PolymarketSmartMoneyItem, PolymarketSmartMoneyParams, PolymarketTradesItem, PolymarketTradesParams, PolymarketVolumeSplitItem, PolymarketVolumeSplitParams, PolymarketVolumesItem, PolymarketVolumesParams } from '../types';

export const polymarket = {
  /** Returns Polymarket events with nested markets, optionally filtered by `event_slug`. Each event includes aggregated status, volume, and a list of markets with `side_a`/`side_b` outcomes. **Data refresh:** ~30 minutes */
  events: (params: PolymarketEventsParams): Promise<ApiResponse<PolymarketEventsItem>> =>
    get('prediction-market/polymarket/events', params as any),

  /** Returns a ranked leaderboard of Polymarket traders by realized PnL, volume, or trade count. Sortable by `pnl`, `volume`, or `trade_count`. Each entry includes the wallet address and aggregate trading statistics. **Data refresh:** ~5 minutes. */
  leaderboard: (params?: PolymarketLeaderboardParams): Promise<ApiResponse<PolymarketLeaderboardItem>> =>
    get('prediction-market/polymarket/leaderboard', params as any),

  /** Returns Polymarket markets, optionally filtered by `market_slug`. Each market includes `side_a` and `side_b` outcomes. Current prices are available via `/polymarket/prices` using the `condition_id`. **Data refresh:** ~30 minutes */
  markets: (params: PolymarketMarketsParams): Promise<ApiResponse<PolymarketMarketsItem>> =>
    get('prediction-market/polymarket/markets', params as any),

  /** Daily open interest time series showing total value locked in a Polymarket market. **Data refresh:** ~30 minutes */
  open_interest: (params: PolymarketOpenInterestParams): Promise<ApiResponse<PolymarketOpenInterestItem>> =>
    get('prediction-market/polymarket/open-interest', params as any),

  /** Historical orderbook snapshots for a Polymarket token. Returns raw bid/ask depth levels. Timestamps in milliseconds. Data refresh: ~5 minutes */
  orderbooks: (params: PolymarketOrderbooksParams): Promise<ApiResponse<PolymarketOrderbooksItem>> =>
    get('prediction-market/polymarket/orderbooks', params as any),

  /** Given a specific wallet address, returns that wallet's open positions on Polymarket markets. This is a single-wallet lookup — you must provide the wallet `address`. **Not what you need?** - To discover top/smart wallets across all of Polymarket, use `polymarket-smart-money` (view=positioning for aggregate signals, view=trades for individual whale trades). - To find top traders by PnL or volume, use `polymarket-leaderboard`. **Data refresh:** ~30 minutes */
  positions: (params: PolymarketPositionsParams): Promise<ApiResponse<PolymarketPositionsItem>> =>
    get('prediction-market/polymarket/positions', params as any),

  /** OHLCV candlestick data for charting a Polymarket market — open, high, low, close, volume per candle. Use this for rendering price charts with candlestick or bar visualizations. For simple price time series (one price per interval), use `prices` instead. Data refresh: ~30 minutes */
  price_ohlcv: (params?: PolymarketPriceOhlcvParams): Promise<ApiResponse<PolymarketPriceOhlcvItem>> =>
    get('prediction-market/polymarket/price-ohlcv/{condition_id}', params as any),

  /** Simple price time series for a Polymarket market — one price point per interval. Use this for tracking price trends over time. For OHLCV candlestick data (open/high/low/close for charting libraries), use `price-ohlcv` instead. **Data refresh:** ~30 minutes */
  prices: (params: PolymarketPricesParams): Promise<ApiResponse<PolymarketPricesItem>> =>
    get('prediction-market/polymarket/prices', params as any),

  /** Smart wallet analytics for Polymarket markets. view=positioning (default): Aggregate smart wallet direction per market — net bullish/bearish signal and conviction. view=trades: Individual $10K+ trades with wallet address, amount, outcome, price, and wallet age. **Data refresh:** ~5 minutes */
  smart_money: (params?: PolymarketSmartMoneyParams): Promise<ApiResponse<PolymarketSmartMoneyItem>> =>
    get('prediction-market/polymarket/smart-money', params as any),

  /** Trade and activity history for a Polymarket market or wallet. Filter by market (condition_id), wallet (address), outcome (Yes/No), minimum trade size, and time range. Use type=redemption for splits/merges/redemptions, type=all for everything. **Data refresh:** ~5 minutes */
  trades: (params?: PolymarketTradesParams): Promise<ApiResponse<PolymarketTradesItem>> =>
    get('prediction-market/polymarket/trades', params as any),

  /** Volume split by YES/NO outcome sides per interval (hour/day/week), plus total volume and trade count. Use this to see directional volume bias. For aggregate volume without YES/NO breakdown, use `volumes` instead. Data refresh: ~30 minutes */
  volume_split: (params?: PolymarketVolumeSplitParams): Promise<ApiResponse<PolymarketVolumeSplitItem>> =>
    get('prediction-market/polymarket/volume-split/{condition_id}', params as any),

  /** Aggregate trading volume (USD) and trade count as a time series. Use this for volume trend analysis. For YES/NO volume breakdown by outcome side, use `volume-split` instead. **Data refresh:** ~30 minutes */
  volumes: (params?: PolymarketVolumesParams): Promise<ApiResponse<PolymarketVolumesItem>> =>
    get('prediction-market/polymarket/volumes', params as any),

};

