// Auto-generated by gen_sdk.py — do not edit.

import { get, post } from '../client';
import type { ApiResponse, PolymarketActivityItem, PolymarketActivityParams, PolymarketEventsItem, PolymarketEventsParams, PolymarketMarketsItem, PolymarketMarketsParams, PolymarketOpenInterestItem, PolymarketOpenInterestParams, PolymarketPositionsItem, PolymarketPositionsParams, PolymarketPricesItem, PolymarketPricesParams, PolymarketRankingItem, PolymarketRankingParams, PolymarketTradesItem, PolymarketTradesParams, PolymarketVolumesItem, PolymarketVolumesParams } from '../types';

export const polymarket = {
  /** Returns trade and redemption activity for a Polymarket wallet. **Data refresh:** ~30 minutes */
  activity: (params: PolymarketActivityParams): Promise<ApiResponse<PolymarketActivityItem>> =>
    get('prediction-market/polymarket/activity', params as any),

  /** Returns Polymarket events with nested markets, optionally filtered by `event_slug`. Each event includes aggregated status, volume, and a list of markets with `side_a`/`side_b` outcomes. **Data refresh:** ~30 minutes */
  events: (params: PolymarketEventsParams): Promise<ApiResponse<PolymarketEventsItem>> =>
    get('prediction-market/polymarket/events', params as any),

  /** Returns Polymarket markets, optionally filtered by `market_slug`. Each market includes `side_a` and `side_b` outcomes. Current prices are available via `/polymarket/prices` using the `condition_id`. **Data refresh:** ~30 minutes */
  markets: (params: PolymarketMarketsParams): Promise<ApiResponse<PolymarketMarketsItem>> =>
    get('prediction-market/polymarket/markets', params as any),

  /** Returns daily open interest history for a Polymarket market. **Data refresh:** ~30 minutes */
  open_interest: (params: PolymarketOpenInterestParams): Promise<ApiResponse<PolymarketOpenInterestItem>> =>
    get('prediction-market/polymarket/open-interest', params as any),

  /** Returns wallet positions on Polymarket markets. **Data refresh:** ~30 minutes */
  positions: (params: PolymarketPositionsParams): Promise<ApiResponse<PolymarketPositionsItem>> =>
    get('prediction-market/polymarket/positions', params as any),

  /** Returns aggregated price history for a Polymarket market. Use `interval=latest` for the most recent price snapshot. **Data refresh:** ~30 minutes */
  prices: (params: PolymarketPricesParams): Promise<ApiResponse<PolymarketPricesItem>> =>
    get('prediction-market/polymarket/prices', params as any),

  /** Returns top-ranked Polymarket markets. **Sort by:** `volume_24h`, `volume_7d`, `open_interest`, or `trade_count`. **Filters:** `status` and `end_before`. **Data refresh:** ~30 minutes */
  ranking: (params?: PolymarketRankingParams): Promise<ApiResponse<PolymarketRankingItem>> =>
    get('prediction-market/polymarket/ranking', params as any),

  /** Returns paginated trade records for a Polymarket market or wallet. **Filters:** `condition_id` (market) or `address` (wallet), plus `outcome_label`, `min_amount`, and date range. At least one of `condition_id` or `address` is required. **Sort:** `newest`, `oldest`, or `largest`. **Data refresh:** ~30 minutes */
  trades: (params?: PolymarketTradesParams): Promise<ApiResponse<PolymarketTradesItem>> =>
    get('prediction-market/polymarket/trades', params as any),

  /** Returns trading volume and trade count history for a Polymarket market. **Data refresh:** ~30 minutes */
  volumes: (params: PolymarketVolumesParams): Promise<ApiResponse<PolymarketVolumesItem>> =>
    get('prediction-market/polymarket/volumes', params as any),

};

