// Auto-generated by gen_sdk.py — do not edit.

import { get, post } from '../client';
import type { ApiCursorResponse, ApiResponse, SearchAirdropItem, SearchAirdropParams, SearchEventsItem, SearchEventsParams, SearchFundItem, SearchFundParams, SearchKalshiItem, SearchKalshiParams, SearchNewsItem, SearchNewsParams, SearchPolymarketItem, SearchPolymarketParams, SearchPredictionMarketItem, SearchPredictionMarketParams, SearchProjectItem, SearchProjectParams, SearchSocialPeopleItem, SearchSocialPeopleParams, SearchSocialPostsItem, SearchSocialPostsParams, SearchWalletItem, SearchWalletParams, SearchWebItem, SearchWebParams } from '../types';

export const search = {
  /** Searches and filters airdrop opportunities. **Filters:** keyword, status, reward type, task type. Returns paginated results with optional task details. */
  airdrop: (params?: SearchAirdropParams): Promise<ApiResponse<SearchAirdropItem>> =>
    get('search/airdrop', params as any),

  /** Searches project events by keyword, optionally filtered by `type`. **Valid types:** `launch`, `upgrade`, `partnership`, `news`, `airdrop`, `listing`, `twitter`. **Lookup:** by UUID (`id`) or name (`q`). Returns 404 if the project is not found. */
  events: (params?: SearchEventsParams): Promise<ApiResponse<SearchEventsItem>> =>
    get('search/events', params as any),

  /** Searches funds by keyword. **Included fields:** name, tier, type, logo, top invested projects. */
  fund: (params: SearchFundParams): Promise<ApiResponse<SearchFundItem>> =>
    get('search/fund', params as any),

  /** **[DEPRECATED]** Use `GET /v1/search/prediction-market?platform=kalshi` instead. This endpoint will continue to work but will not receive new features. --- Searches Kalshi events by keyword and/or category. **Filters:** - Keyword matching event title, subtitle, or market title - Category At least one of `q` or `category` is required. Returns events with nested markets. **Data refresh:** ~30 minutes */
  kalshi: (params?: SearchKalshiParams): Promise<ApiResponse<SearchKalshiItem>> =>
    get('search/kalshi', params as any),

  /** Searches crypto news articles by keyword. Returns top 10 results ranked by relevance with highlighted matching fragments. */
  news: (params: SearchNewsParams): Promise<ApiResponse<SearchNewsItem>> =>
    get('search/news', params as any),

  /** **[DEPRECATED]** Use `GET /v1/search/prediction-market?platform=polymarket` instead. This endpoint will continue to work but will not receive new features. --- Searches Polymarket events by keyword, tags, and/or category. **Filters:** - Keyword matching market question, event title, or description - Comma-separated tag labels - Surf-curated category At least one of `q`, `tags`, or `category` is required. Returns events with nested markets ranked by volume. **Data refresh:** ~30 minutes */
  polymarket: (params?: SearchPolymarketParams): Promise<ApiResponse<SearchPolymarketItem>> =>
    get('search/polymarket', params as any),

  /** Browse and search prediction markets across all supported platforms. Filter by platform, category, status, keyword search, and smart money direction. Each result includes volume, open interest, trade counts, and smart money signals. Supports single-market lookup via `condition_id` or `market_ticker`. **Data refresh:** ~5 minutes. */
  prediction_market: (params?: SearchPredictionMarketParams): Promise<ApiResponse<SearchPredictionMarketItem>> =>
    get('search/prediction-market', params as any),

  /** Searches crypto projects by keyword. **Included fields:** name, description, chains, logo. */
  project: (params: SearchProjectParams): Promise<ApiResponse<SearchProjectItem>> =>
    get('search/project', params as any),

  /** Searches X (Twitter) users by keyword. **Included fields:** handle, display name, bio, follower count, avatar. */
  social_people: (params: SearchSocialPeopleParams): Promise<ApiCursorResponse<SearchSocialPeopleItem>> =>
    get('search/social/people', params as any),

  /** Searches X (Twitter) posts by keyword or `from:handle` syntax. **Included fields:** author, content, engagement metrics, timestamp. **Pagination:** check `meta.has_more`; if true, pass `meta.next_cursor` as the `cursor` query parameter in the next request. */
  social_posts: (params: SearchSocialPostsParams): Promise<ApiCursorResponse<SearchSocialPostsItem>> =>
    get('search/social/posts', params as any),

  /** Searches wallets by ENS name, address label, or address prefix. Returns matching wallet addresses with entity labels. */
  wallet: (params: SearchWalletParams): Promise<ApiResponse<SearchWalletItem>> =>
    get('search/wallet', params as any),

  /** Searches web pages, articles, and content by keyword. **Filters:** domain via `site` (e.g. `coindesk.com`). **Included fields:** titles, URLs, content snippets. */
  web: (params: SearchWebParams): Promise<ApiResponse<SearchWebItem>> =>
    get('search/web', params as any),

};

