// Auto-generated by gen_sdk.py — do not edit.

import { get, post } from '../client';
import type { ApiResponse, TokenDexTradesItem, TokenDexTradesParams, TokenHoldersItem, TokenHoldersParams, TokenTokenomicsItem, TokenTokenomicsParams, TokenTransfersItem, TokenTransfersParams } from '../types';

export const token = {
  /** Returns recent DEX swap events for a token contract address. **Covered DEXes:** `uniswap`, `sushiswap`, `curve`, `balancer`. **Included fields:** trading pair, amounts, USD value, taker address. **Data refresh:** ~24 hours · **Chains:** Ethereum, Base */
  dex_trades: (params: TokenDexTradesParams): Promise<ApiResponse<TokenDexTradesItem>> =>
    get('token/dex-trades', params as any),

  /** Returns top token holders for a contract address. **Included fields:** wallet address, balance, and percentage. **Lookup:** by `address` and `chain`. Supports EVM chains and Solana. */
  holders: (params: TokenHoldersParams): Promise<ApiResponse<TokenHoldersItem>> =>
    get('token/holders', params as any),

  /** Returns token unlock time-series with amounts and allocation breakdowns. **Lookup:** by project UUID (`id`) or token `symbol`. Filter by date range with `from`/`to` — defaults to the current calendar month when omitted. Returns 404 if no token found. */
  tokenomics: (params?: TokenTokenomicsParams): Promise<ApiResponse<TokenTokenomicsItem>> =>
    get('token/tokenomics', params as any),

  /** Returns recent transfer events **for a specific token** (ERC-20/TRC-20 contract). Pass the **token contract address** in `address` — returns every on-chain transfer of that token regardless of sender/receiver. **Included fields:** sender, receiver, raw amount, block timestamp. Use this to analyze a token's on-chain activity (e.g. large movements, distribution patterns). **Lookup:** `address` (token contract) + `chain`. Sort by `asc` or `desc`. **Data refresh:** ~24 hours · **Chains:** Ethereum, Base, TRON (Solana uses a different source with no delay) */
  transfers: (params: TokenTransfersParams): Promise<ApiResponse<TokenTransfersItem>> =>
    get('token/transfers', params as any),

};

