// Auto-generated by gen_sdk.py — do not edit.

import { get, post } from '../client';
import type { ApiResponse, V2KalshiOrderbooksItem, V2KalshiOrderbooksParams, V2PolymarketCandlesticksItem, V2PolymarketCandlesticksParams, V2PolymarketOrderbooksItem, V2PolymarketOrderbooksParams, V2PolymarketVolumeChartItem, V2PolymarketVolumeChartParams, V2PolymarketVolumeTimeseriesItem, V2PolymarketVolumeTimeseriesParams } from '../types';

export const v2 = {
  /** Historical orderbook snapshots for a Kalshi market. Returns yes-side bid/ask levels. Timestamps in milliseconds, prices in cents. Data refresh: ~5 minutes */
  kalshi_orderbooks: (params: V2KalshiOrderbooksParams): Promise<ApiResponse<V2KalshiOrderbooksItem>> =>
    get('gateway/v2/kalshi/orderbooks', params as any),

  /** OHLCV candlestick data for a Polymarket market. Prices normalized to YES side. Data refresh: ~30 minutes */
  polymarket_candlesticks: (params?: V2PolymarketCandlesticksParams): Promise<ApiResponse<V2PolymarketCandlesticksItem>> =>
    get('gateway/v2/polymarket/candlesticks/{condition_id}', params as any),

  /** Cumulative volume time series for a Polymarket token. Data refresh: ~30 minutes */
  polymarket_volume_timeseries: (params?: V2PolymarketVolumeTimeseriesParams): Promise<ApiResponse<V2PolymarketVolumeTimeseriesItem>> =>
    get('gateway/v2/polymarket/markets/{token_id}/volume', params as any),

  /** Historical orderbook snapshots for a Polymarket token. Returns raw bid/ask depth levels. Timestamps in milliseconds. Data refresh: ~5 minutes */
  polymarket_orderbooks: (params: V2PolymarketOrderbooksParams): Promise<ApiResponse<V2PolymarketOrderbooksItem>> =>
    get('gateway/v2/polymarket/orderbooks', params as any),

  /** Volume breakdown by outcome (YES/NO) for a Polymarket market. Data refresh: ~30 minutes */
  polymarket_volume_chart: (params?: V2PolymarketVolumeChartParams): Promise<ApiResponse<V2PolymarketVolumeChartItem>> =>
    get('gateway/v2/polymarket/volume-chart/{condition_id}', params as any),

};

