// Auto-generated by gen_sdk.py — do not edit.

import { get, post } from '../client';
import type { ApiObjectResponse, ApiResponse, WalletDetailData, WalletDetailParams, WalletHistoryItem, WalletHistoryParams, WalletLabelsBatchItem, WalletLabelsBatchParams, WalletNetWorthItem, WalletNetWorthParams, WalletProtocolsItem, WalletProtocolsParams, WalletTransfersItem, WalletTransfersParams } from '../types';

export const wallet = {
  /** Get multiple wallet sub-resources in a single request. Lookup by `address`. Use `fields` to select: `balance`, `tokens`, `labels`, `nft`. Partial failures return available fields with per-field error info. Returns 422 if `fields` is invalid. */
  detail: (params?: WalletDetailParams): Promise<ApiObjectResponse<WalletDetailData>> =>
    get('wallet/detail', params as any),

  /** Get full transaction history for a wallet — swaps, transfers, and contract interactions. Lookup by `address`. Filter by `chain` — supports `ethereum`, `polygon`, `bsc`, `arbitrum`, `optimism`, `avalanche`, `fantom`, `base`. */
  history: (params?: WalletHistoryParams): Promise<ApiResponse<WalletHistoryItem>> =>
    get('wallet/history', params as any),

  /** Get entity labels for multiple wallet addresses. Pass up to 100 comma-separated addresses via the `addresses` query parameter. Returns entity name, type, and labels per address. */
  labels_batch: (params?: WalletLabelsBatchParams): Promise<ApiResponse<WalletLabelsBatchItem>> =>
    get('wallet/labels-batch', params as any),

  /** Get a time-series of the wallet's total net worth in USD. Returns ~288 data points at 5-minute intervals covering the last 24 hours. Fixed window — no custom time range supported. */
  net_worth: (params?: WalletNetWorthParams): Promise<ApiResponse<WalletNetWorthItem>> =>
    get('wallet/net-worth', params as any),

  /** Get all DeFi protocol positions for a wallet — lending, staking, LP, and farming with token breakdowns and USD values. Lookup by `address`. */
  protocols: (params?: WalletProtocolsParams): Promise<ApiResponse<WalletProtocolsItem>> =>
    get('wallet/protocols', params as any),

  /** Get recent token transfers **sent or received by a wallet**. Pass the **wallet address** in `address` — returns all ERC-20/SPL token transfers where this wallet is the sender or receiver. Each record includes token contract, counterparty, raw amount, and block timestamp. Use this to audit a wallet's token flow (e.g. inflows, outflows, airdrop receipts). Lookup: `address` (wallet, raw 0x hex or base58 — ENS not supported). Filter by `chain` — supports `ethereum`, `base`, `solana`. Data refresh: ~24 hours · Chain: Ethereum, Base (Solana uses a different source with no delay) */
  transfers: (params?: WalletTransfersParams): Promise<ApiResponse<WalletTransfersItem>> =>
    get('wallet/transfers', params as any),

};

