// Auto-generated by gen_sdk.py — do not edit.

import { get, post } from '../client';
import type { ApiObjectResponse, ApiResponse, WalletDetailData, WalletDetailParams, WalletHistoryItem, WalletHistoryParams, WalletLabelsBatchItem, WalletLabelsBatchParams, WalletNetWorthItem, WalletNetWorthParams, WalletProtocolsItem, WalletProtocolsParams, WalletTransfersItem, WalletTransfersParams } from '../types';

export const wallet = {
  /** Returns multiple wallet sub-resources in a single request. **Available fields** (via `fields`): `balance`, `tokens`, `labels`, `nft`. **Lookup:** by `address`. Partial failures return available fields with per-field error info. Returns 422 if `fields` is invalid. */
  detail: (params: WalletDetailParams): Promise<ApiObjectResponse<WalletDetailData>> =>
    get('wallet/detail', params as any),

  /** Returns full transaction history for a wallet — swaps, transfers, and contract interactions. **Lookup:** by `address`. Filter by `chain` — supports `ethereum`, `polygon`, `bsc`, `arbitrum`, `optimism`, `avalanche`, `fantom`, `base`. */
  history: (params: WalletHistoryParams): Promise<ApiResponse<WalletHistoryItem>> =>
    get('wallet/history', params as any),

  /** Returns entity labels for multiple wallet addresses. Pass up to 100 comma-separated addresses via the `addresses` query parameter. **Included fields:** entity name, type, and labels per address. */
  labels_batch: (params: WalletLabelsBatchParams): Promise<ApiResponse<WalletLabelsBatchItem>> =>
    get('wallet/labels/batch', params as any),

  /** Returns a time-series of the wallet's total net worth in USD. Returns ~288 data points at 5-minute intervals covering the last 24 hours. Fixed window — no custom time range supported. */
  net_worth: (params: WalletNetWorthParams): Promise<ApiResponse<WalletNetWorthItem>> =>
    get('wallet/net-worth', params as any),

  /** Returns all DeFi protocol positions for a wallet — lending, staking, LP, and farming with token breakdowns and USD values. **Lookup:** by `address`. */
  protocols: (params: WalletProtocolsParams): Promise<ApiResponse<WalletProtocolsItem>> =>
    get('wallet/protocols', params as any),

  /** Returns recent token transfers **sent or received by a wallet**. Pass the **wallet address** in `address` — returns all ERC-20/SPL token transfers where this wallet is the sender or receiver. **Included fields:** token contract, counterparty, raw amount, block timestamp. Use this to audit a wallet's token flow (e.g. inflows, outflows, airdrop receipts). **Lookup:** `address` (wallet, raw 0x hex or base58 — ENS not supported). Filter by `chain` — supports `ethereum`, `base`, `solana`. **Data refresh:** ~24 hours · **Chains:** Ethereum, Base (Solana uses a different source with no delay) */
  transfers: (params: WalletTransfersParams): Promise<ApiResponse<WalletTransfersItem>> =>
    get('wallet/transfers', params as any),

};

