// Auto-generated by gen_sdk.py — do not edit.

import { get, post } from '../client';
import type { ApiObjectResponse, WebFetchData, WebFetchParams } from '../types';

export const web = {
  /** Fetches a web page and converts it to clean, LLM-friendly markdown. **Options:** - `target_selector` — extract specific page sections - `remove_selector` — strip unwanted elements Returns 400 if the URL is invalid or unreachable. */
  fetch: (params: WebFetchParams): Promise<ApiObjectResponse<WebFetchData>> =>
    get('web/fetch', params as any),

};

