// Auto-generated by gen_sdk.py — do not edit.

import { get, post } from './client';
import { exchange } from './categories/exchange';
import { fund } from './categories/fund';
import { kalshi } from './categories/kalshi';
import { market } from './categories/market';
import { matching } from './categories/matching';
import { news } from './categories/news';
import { onchain } from './categories/onchain';
import { polymarket } from './categories/polymarket';
import { prediction_market } from './categories/prediction_market';
import { project } from './categories/project';
import { search } from './categories/search';
import { social } from './categories/social';
import { token } from './categories/token';
import { v2 } from './categories/v2';
import { wallet } from './categories/wallet';
import { web } from './categories/web';

export const dataApi = {
  /** Escape hatch: raw GET to any endpoint path. */
  get,
  /** Escape hatch: raw POST to any endpoint path. */
  post,
  exchange,
  fund,
  kalshi,
  market,
  matching,
  news,
  onchain,
  polymarket,
  prediction_market,
  project,
  search,
  social,
  token,
  v2,
  wallet,
  web,
};

export type DataApi = typeof dataApi;

